name: build_test_deploy
on: push
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - run: npm install
      - run: npm test
      - run: npm run build
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build_test
    environment:
      name: staging
      url: https://staging.myapp.it
    if: ${{ github.ref == 'refs/heads/staging' }}
    steps:
      - run: echo "Deploying to staging...${{ env.URL_MYAPP }}"
  deploy-production:
    runs-on: ubuntu-latest
    needs: build_test
    environment:
      name: production
      url: https://production.myapp.it
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - run: echo "Deploying main to production...${{ env.URL_MYAPP }}"
    
    
