name: build_test_deploy
on: push
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - run: npm install
      - run: npm test
      - run: npm build
  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    if: ${{ github.ref == "refs/head/staging" }}
    steps:
      - run: echo "Deploying..."
    
